package protections

func groupHTTPCompliance() Group {
	return Group{
		ID:          "http-compliance",
		Name:        "HTTP compliance",
		Description: "HTTP RFC-compliance enforcement. Catches malformed requests, unusual headers, character-encoding tricks, and policy violations.",
		WhyDisable:  "Disable carefully when your upstream is non-RFC-strict (e.g., a legacy proxy that mangles framing). Increases attack surface; usually wrong.",
		Buckets: []L2{
			{
				ID:          "http-compliance-request-framing",
				Name:        "Request framing",
				Description: "Request-line validation, body presence on GET/HEAD, content-length consistency, smuggling fingerprints.",
				Leaves: []Leaf{
					{ID: "http-compliance-malformed-request-line", Default: On, CWE: []int{444}, RuleIDs: []string{"920100"},
						WhatItDoes: "Detects malformed HTTP request lines — GET / HTTP/1.1\\n without proper CRLF, missing version, etc.",
						WhyDisable: "Disable for upstreams that emit non-RFC request lines."},
					{ID: "http-compliance-multipart-boundaries", Default: On, CWE: []int{444}, RuleIDs: []string{"920120", "920121"},
						WhatItDoes: "Detects multipart/form-data bypass attempts — non-standard boundary syntax used to confuse parsers.",
						WhyDisable: "Moderate FP risk — some real-world multipart implementations (older Python requests, mobile SDKs, embedded HTTP clients) emit non-strict boundaries. Disable if your client library does."},
					{ID: "http-compliance-content-length", Default: On, CWE: []int{444}, RuleIDs: []string{"920160"},
						WhatItDoes: "Catches non-numeric Content-Length header values.",
						WhyDisable: "Rarely worth disabling."},
					{ID: "http-compliance-get-with-body", Default: On, CWE: []int{444}, RuleIDs: []string{"920170", "920171"},
						WhatItDoes: "Detects GET or HEAD requests carrying a body or Transfer-Encoding header — RFC says they shouldn't.",
						WhyDisable: "Disable if your API allows GET requests with bodies — for example, some search APIs do this."},
					{ID: "http-compliance-post-without-length", Default: On, CWE: []int{444}, RuleIDs: []string{"920180"},
						WhatItDoes: "Detects POST requests without Content-Length and without Transfer-Encoding — ambiguous body length.",
						WhyDisable: "Rarely worth disabling."},
					{ID: "http-compliance-conflicting-length", Default: On, CWE: []int{444}, RuleIDs: []string{"920181"},
						WhatItDoes: "Detects requests carrying both Content-Length and Transfer-Encoding — the classic request-smuggling fingerprint.",
						WhyDisable: "Rarely worth disabling."},
					{ID: "http-compliance-http-version", Default: On, CWE: []int{444}, RuleIDs: []string{"920430"},
						WhatItDoes: "Detects HTTP versions outside the route's allow-list.",
						WhyDisable: "Disable if your route accepts HTTP/0.9 or some non-standard version."},
					{ID: "http-compliance-method-override-param", Default: Off, CWE: []int{444}, RuleIDs: []string{"native", "920650"},
						WhatItDoes: "Detects HTTP-method override attempts via _method parameter.",
						WhyEnable:  "Enable to flag _method parameter overrides. Used by some frameworks (Rails) but also by attackers to bypass method-policy filters."},
					{ID: "http-compliance-uri-fragments", Default: On, CWE: []int{444}, RuleIDs: []string{"920610"},
						WhatItDoes: "Detects raw #fragment in the URI sent to the server — should normally be client-side only.",
						WhyDisable: "Disable for SPAs that intentionally pass #fragment to the server."},
				},
			},
			{
				ID:          "http-compliance-headers",
				Name:        "Headers",
				Description: "Header presence and shape validation — Host, Accept, User-Agent, Content-Type, Accept-Encoding, restricted headers, Range, Connection.",
				Leaves: []Leaf{
					{ID: "http-compliance-host-header", Default: On, CWE: []int{20}, RuleIDs: []string{"920280", "920290", "920350"},
						WhatItDoes: "Catches missing/empty Host header and IP-literal Host values.",
						WhyDisable: "Disable for legacy clients that don't send Host, or for routes that receive health-check probes or load-balancer probes connecting by IP (the rule flags IP-literal Host values, which are routine in those flows)."},
					{ID: "http-compliance-accept-header", Default: Off, CWE: []int{20}, RuleIDs: []string{"920300", "920310", "920311", "920600"},
						WhatItDoes: "Empty/missing Accept and illegal Accept-charset parameter detection.",
						WhyEnable:  "Enable if your app is browser-only and your clients always send Accept. Off by default because many JSON APIs are called from curl, internal service-to-service code, mobile SDKs, and SDK-generated clients that legitimately omit Accept. The signal is \"automation,\" not \"attack.\""},
					{ID: "http-compliance-user-agent-header", Default: Off, CWE: []int{20}, RuleIDs: []string{"920320", "920330"},
						WhatItDoes: "Missing or empty User-Agent header detection.",
						WhyEnable:  "Enable if your app expects browser traffic only. Off by default because empty User-Agent is the normal case for curl without -A, internal service-to-service calls, embedded device firmware, and historical Go http.Client. No real attack class is gated by \"must have a User-Agent header.\""},
					{ID: "http-compliance-content-type-header", Default: On, CWE: []int{20}, RuleIDs: []string{"920340", "920470", "920480", "920530", "920620", "920640"},
						WhatItDoes: "CT header policy — illegal CT values, multiple CTs, CT charset validity, CT missing on bodied requests.",
						WhyDisable: "Rarely worth disabling."},
					{ID: "http-compliance-accept-encoding", Default: On, CWE: []int{20}, RuleIDs: []string{"920520", "920521"},
						WhatItDoes: "Accept-Encoding length cap and illegal-value detection.",
						WhyDisable: "Disable for clients that send long or unusual Accept-Encoding values."},
					{ID: "http-compliance-restricted-headers", Default: On, CWE: []int{20}, RuleIDs: []string{"920450", "920451", "920490", "920510"},
						WhatItDoes: "Restricted-header denylist — flags headers like X-Up-Devcap-Post-Charset and Cache-Control variants that aren't in the allow-list.",
						WhyDisable: "Disable if you legitimately send headers in the restricted list — for example, Cache-Control with non-standard directives."},
					{ID: "http-compliance-range-header", Default: On, CWE: []int{400}, RuleIDs: []string{"920190", "920200", "920201", "920202", "920660"},
						WhatItDoes: "Range header anomalies — invalid last-byte values, too many byte-ranges, obsolete Request-Range header.",
						WhyDisable: "Disable if upstream serves PDFs/videos with many byte-ranges."},
					{ID: "http-compliance-connection-header", Default: On, CWE: []int{444}, RuleIDs: []string{"920210"},
						WhatItDoes: "Detects multiple/conflicting Connection header values.",
						WhyDisable: "Rarely worth disabling."},
				},
			},
			{
				ID:          "http-compliance-character-encoding",
				Name:        "Character encoding",
				Description: "Character-encoding abuse — URL encoding, UTF-8 abuse, null bytes, invalid characters.",
				Leaves: []Leaf{
					{ID: "http-compliance-double-url-encoding", Default: Off, CWE: []int{177}, RuleIDs: []string{"native", "920230", "920240", "920460"},
						WhatItDoes: "Multiple URL encoding detection (%2520 instead of %20, etc.). Native and CRS detection backends both contribute.",
						WhyEnable:  "Enable on routes where multi-URL-encoded inputs warrant detection. Off by default because legitimate inputs sometimes need double-encoding."},
					{ID: "http-compliance-utf8-tricks", Default: On, CWE: []int{176}, RuleIDs: []string{"native", "920250", "920260", "920540"},
						WhatItDoes: "UTF-8 abuse — overlong sequences, full/half-width abuse, surrogate-pair tricks used to bypass naive validators.",
						WhyDisable: "Disable for routes serving Unicode-heavy content."},
					{ID: "http-compliance-null-bytes", Default: On, CWE: []int{158}, RuleIDs: []string{"native", "920270"},
						WhatItDoes: "Catches literal null bytes (\\x00) in request inputs — used to truncate strings in C-string-aware downstream code.",
						WhyDisable: "Rarely worth disabling."},
					{ID: "http-compliance-non-printable-characters", Default: Off, CWE: []int{176}, RuleIDs: []string{"920271", "920272", "920273", "920274", "920275"},
						WhatItDoes: "Non-printable / non-ASCII / strict-set character detection — increasingly strict at higher paranoia tiers.",
						WhyEnable:  "Enable on locked-down routes where ASCII-only inputs are expected."},
				},
			},
			{
				ID:          "http-compliance-allowed-shapes",
				Name:        "Allowed shapes",
				Description: "What the route allows (content-type, file extension) and what it explicitly forbids (backup-file probes).",
				Leaves: []Leaf{
					{ID: "http-compliance-allowed-content-types", Default: On, CWE: []int{20}, RuleIDs: []string{"920420"},
						WhatItDoes: "Catches Content-Type values not in the route's allow-list.",
						WhyDisable: "Disable when content-type allow-list is enforced at the app layer."},
					{ID: "http-compliance-blocked-extensions", Default: On, CWE: []int{538}, RuleIDs: []string{"920440"},
						WhatItDoes: "Catches URL file extensions in the restricted list (.bak, .git, .ini).",
						WhyDisable: "Disable for static-content routes serving many file types."},
					{ID: "http-compliance-backup-file-probes", Default: On, CWE: []int{530}, RuleIDs: []string{"920500"},
						WhatItDoes: "Backup-file-extension probe detection (.bak, .swp, .old, .~) — fingerprint of recon attempts.",
						WhyDisable: "Rarely worth disabling."},
				},
			},
		},
	}
}

func groupHTTPAttacks() Group {
	return Group{
		ID:          "http-attacks",
		Name:        "HTTP attacks",
		Description: "Explicit protocol-level attacks — smuggling, response splitting, header injection, parameter pollution.",
		WhyDisable:  "Risky — disable only when your upstream provably handles these attacks itself or operates behind a managed CDN that does. Most leaves should rarely be off; prefer disabling individual leaves over the whole family.",
		Leaves: []Leaf{
			{ID: "http-attacks-request-smuggling", Default: On, CWE: []int{444}, RuleIDs: []string{"native", "921110"},
				WhatItDoes: "HTTP request smuggling detection — conflicting framing headers used to desync front-end and back-end parsers.",
				WhyDisable: "Rarely worth disabling — smuggling attacks are dangerous and the FP rate is low. Native and CRS detection both contribute."},
			{ID: "http-attacks-response-splitting", Default: On, CWE: []int{113}, RuleIDs: []string{"921120", "921130"},
				WhatItDoes: "HTTP response-splitting attack — CR/LF injected into header values to inject extra headers or a second response.",
				WhyDisable: "Rarely worth disabling."},
			{ID: "http-attacks-header-crlf-injection", Default: On, CWE: []int{93, 113}, RuleIDs: []string{"native", "921140", "921150", "921151", "921160", "921190"},
				WhatItDoes: "CR/LF injection into headers via payload, including header-name detection.",
				WhyDisable: "Rarely worth disabling. Native and CRS detection both contribute."},
			{ID: "http-attacks-duplicate-parameters", Default: Off, CWE: []int{235}, RuleIDs: []string{"921170", "921180", "921210", "921220"},
				WhatItDoes: "HTTP Parameter Pollution — duplicate parameter names and array-notation tricks.",
				WhyEnable:  "Enable for hardened environments where duplicate parameters warrant detection. Off by default because legitimate apps often have intentional duplicates."},
			{ID: "http-attacks-range-dos", Default: Off, CWE: []int{400}, RuleIDs: []string{"921230"},
				WhatItDoes: "Range header attack patterns (Apache CVE-2011-3192-style requests with many overlapping byte ranges that exhaust memory).",
				WhyEnable:  "Enable when you've ruled out legitimate large-byte-range requests."},
			{ID: "http-attacks-apache-mod-proxy", Default: On, CWE: []int{444}, RuleIDs: []string{"921240"},
				WhatItDoes: "Detects Apache mod_proxy abuse patterns.",
				WhyDisable: "Disable if you don't run Apache mod_proxy upstream."},
			{ID: "http-attacks-rfc2109-cookies", Default: On, CWE: []int{565}, RuleIDs: []string{"921250"},
				WhatItDoes: "Detects obsolete RFC 2109 (\"Cookie V1\") syntax — should never appear in modern requests.",
				WhyDisable: "Rarely worth disabling."},
			{ID: "http-attacks-dangerous-content-types", Default: On, CWE: []int{434}, RuleIDs: []string{"921421", "921422"},
				WhatItDoes: "Detects dangerous content types in MIME structure — application/x-shockwave-flash declared outside the MIME container, etc.",
				WhyDisable: "Disable if your app legitimately uses unusual content-type values in body parts."},
		},
	}
}
